### ISSUE TITLE
container stdout

### ISSUE THREAD

**Issue by 1N50MN14** [iamatypeofwalrus/logspout-loggly#1]
First many thanks for the loggly adapter!

Newbie question here, logspout-loggly doesn't seem to pick up on container stdout , "ADDRESS CONTAINERS" is empty and "SOURCE OPTIONS" has an empty `map` ARRAY.

Would appreciate any tips/pointers.

**Comment by iamatypeofwalrus** [comment]
How are you launching the image?

**Comment by kirillrdy** [comment]
@1N50MN14 ensure container is started without -t flag
`logspout will gather logs from other containers that are started without the -t option.`
for more info
https://github.com/gliderlabs/logspout
