### ISSUE TITLE
Issues with structured data

### ISSUE THREAD

**Issue by karthikiyengar** [iamatypeofwalrus/logspout-loggly#11]
Thanks for the adapter. I'm not sure whether this repo is active, but I'll put in an issue nevertheless.

Loggy seems unable to parse JSON that the adapter sends along, it gets interpreted as a string. Is there anything specific we can do to address this?

**Comment by iamatypeofwalrus** [comment]
hey, the adapter makes no assumption about the type of data it's sending to Loggly. As such strings with double quotes (") like JSON messages get escaped on the way out the door.

I'm not actively maintaining this package, nor do I use Loggly anymore. However, I'm more than happy to accept PRs.

**Comment by karthikiyengar** [comment]
Unfortunately, I can't do a lot of Go and I'm considering alternate logging providers.

Thanks for the repository though, pretty helpful :-)
