### ISSUE TITLE
logging stops working

### ISSUE THREAD

**Issue by kirillrdy** [iamatypeofwalrus/logspout-loggly#4]
using http.Post to wirite to loggly sometimes can exceed 1 second which causes logspout to stop sending events on the logstream channel.
As can be seen here
https://github.com/gliderlabs/logspout/blob/master/router/pump.go#L276

To reproduce, just add a time.Sleep inside your SendMessage function.

Some of solutions:
- do slow work in goroutine, I can see there were some plans to use pool of workers.
- convince logspout people to either increase timeout or get rid of it( I am not sure what purpose it has) 
- dont use http.Post to write to logly, use something lighter such as udp
  https://www.loggly.com/docs/basics-of-sending-data/

I just hope this helps someone who is also investigating why logging stops working.
I can see there are a few forks, all seems to focus on debuging some issues.

**Comment by iamatypeofwalrus** [comment]
I have a quick patch that will set a timeout to 1 second and naively using go functions to perform the work.

Long term UDP is a better solution, but I won't be able to fix that for a while. Totally willing to accept Pull Requests (with tests) if you have them!

**Comment by iamatypeofwalrus** [comment]
8a22b76c1c4fe84 implements a naive fix for this issue.
