### ISSUE TITLE
error from client: Post https://...: net/http: request canceled while waiting for connection

### ISSUE THREAD

**Issue by jcrombez** [iamatypeofwalrus/logspout-loggly#5]
I got this when running your image :

```
logspout-loggly2016/02/26 22:16:26 error from client: Post https://logs-01.loggly.com/inputs/my-token: net/http: request canceled while waiting for connection
logspout-loggly2016/02/26 22:16:26 error from client: Post https://logs-01.loggly.com/inputs/my-token: net/http: request canceled while waiting for connection
logspout-loggly2016/02/26 22:16:26 error from client: Post https://logs-01.loggly.com/inputs/my-token: net/http: request canceled while waiting for connection
logspout-loggly2016/02/26 22:16:26 error from client: Post https://logs-01.loggly.com/inputs/my-token: net/http: request canceled while waiting for connection
logspout-loggly2016/02/26 22:16:26 error from client: Post https://logs-01.loggly.com/inputs/my-token: use of closed network connection
logspout-loggly2016/02/26 22:16:26 error from client: Post https://logs-01.loggly.com/inputs/my-token: read tcp xxx.xxx.xxx.xxx:443: use of closed network connection
logspout-loggly2016/02/26 22:16:26 error from client: Post https://logs-01.loggly.com/inputs/my-token: read tcp xxx.xxx.xxx.xxx:443: use of closed network connection
logspout-loggly2016/02/26 22:16:26 error from client: Post https://logs-01.loggly.com/inputs/my-token: read tcp xxx.xxx.xxx.xxx:443: use of closed network connection
logspout-loggly2016/02/26 22:16:26 error from client: Post https://logs-01.loggly.com/inputs/my-token: use of closed network connection
logspout-loggly2016/02/26 22:16:26 error from client: Post https://logs-01.loggly.com/inputs/my-token: read tcp xxx.xxx.xxx.xxx:443: use of closed network connection
```

any idea ?

**Comment by yoo** [comment]
`netstat -an` shows a lot of TIME_WAIT connections.

```
/ # netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 172.17.0.3:59572        54.236.79.251:443       TIME_WAIT   
tcp        0      0 172.17.0.3:59618        54.236.79.251:443       TIME_WAIT   
tcp        0      0 172.17.0.3:42266        54.209.84.18:443        TIME_WAIT   
tcp        0      0 172.17.0.3:37995        54.236.80.3:443         TIME_WAIT   
tcp        0      0 172.17.0.3:59560        54.236.79.251:443       TIME_WAIT   
[...] (truncated output)
```

**Comment by yoo** [comment]
Pull requst #6 should fix this. A docker image including the fix can be found at:
quay.io/eversolve/logspout-loggly

**Comment by jcrombez** [comment]
I tried your image Johnaan, but i have the same problem.

```
logspout-loggly-fork-1 | 2016-02-29T17:21:24.488879386Z # logspout v3-master-custom by gliderlabs
logspout-loggly-fork-1 | 2016-02-29T17:21:24.488967711Z # adapters: udp tcp syslog loggly raw
logspout-loggly-fork-1 | 2016-02-29T17:21:24.488976454Z # options : persist:/mnt/routes
logspout-loggly-fork-1 | 2016-02-29T17:21:24.488980181Z # jobs    : http[logs,routes]:80 pump
logspout-loggly-fork-1 | 2016-02-29T17:21:24.488983748Z # routes  :
logspout-loggly-fork-1 | 2016-02-29T17:21:24.488987208Z #   ADAPTER ADDRESS CONTAINERS  SOURCES OPTIONS
logspout-loggly-fork-1 | 2016-02-29T17:21:24.488992630Z #   loggly  map[]
logspout-loggly-fork-1 | 2016-02-29T17:24:22.623558630Z logspout-loggly2016/02/29 17:24:22 error from client: Post https://logs-01.loggly.com/inputs/<token>: net/http: request canceled while waiting for connection
logspout-loggly-fork-1 | 2016-02-29T17:24:22.623785877Z logspout-loggly2016/02/29 17:24:22 error from client: Post https://logs-01.loggly.com/inputs/<token>: net/http: request canceled while waiting for connection
logspout-loggly-fork-1 | 2016-02-29T17:24:22.625762723Z logspout-loggly2016/02/29 17:24:22 error from client: Post https://logs-01.loggly.com/inputs/<token>: net/http: request canceled while waiting for connection
logspout-loggly-fork-1 | 2016-02-29T17:24:22.775842771Z logspout-loggly2016/02/29 17:24:22 error from client: Post https://logs-01.loggly.com/inputs/<token>: net/http: request canceled while waiting for connection
logspout-loggly-fork-1 | 2016-02-29T17:24:22.776074636Z logspout-loggly2016/02/29 17:24:22 error from client: Post https://logs-01.loggly.com/inputs/<token>: net/http: request canceled while waiting for connection
logspout-loggly-fork-1 | 2016-02-29T17:24:22.778035936Z logspout-loggly2016/02/29 17:24:22 error from client: Post https://logs-01.loggly.com/inputs/<token>: net/http: request canceled while waiting for connection
logspout-loggly-fork-1 | 2016-02-29T17:24:22.906046525Z logspout-loggly2016/02/29 17:24:22 error from client: Post https://logs-01.loggly.com/inputs/<token>: net/http: request canceled while waiting for connection
logspout-loggly-fork-1 | 2016-02-29T17:24:22.906186517Z logspout-loggly2016/02/29 17:24:22 error from client: Post https://logs-01.loggly.com/inputs/<token>: net/http: request canceled while waiting for connection
logspout-loggly-fork-1 | 2016-02-29T17:24:22.906465959Z logspout-loggly2016/02/29 17:24:22 error from client: Post https://logs-01.loggly.com/inputs/<token>: net/http: request canceled while waiting for connection
logspout-loggly-fork-1 | 2016-02-29T17:24:23.039493106Z logspout-loggly2016/02/29 17:24:23 error from client: Post https://logs-01.loggly.com/inputs/<token>: net/http: request canceled while waiting for connection
logspout-loggly-fork-1 | 2016-02-29T17:24:56.877073786Z logspout-loggly2016/02/29 17:24:56 error from client: Post https://logs-01.loggly.com/inputs/<token>: read tcp xxx.xxx.xxx.xxx:443: use of closed network connection
```

**Comment by yoo** [comment]
I should have some time on my hand this weekend. I will add the bulk endpoint https://www.loggly.com/docs/http-bulk-endpoint/ to the program and reduce the worker count. I hope this will fix the issue.

**Comment by jcrombez** [comment]
Great ! good luck :)

**Comment by yoo** [comment]
Okay, I got around to implement the bulk endpoint. Log messages are now dispatched every 2 seconds.  The docker image at quay.io/eversolve/logspout-loggly is up to date with the changes. @jcrombez  maybe you can give it a try and report if it still has problems.

**Comment by jcrombez** [comment]
Sorry i really don't have much time this days, i'll try to find some ASAP to test this if i can.

**Comment by iamatypeofwalrus** [comment]
@JohannWeging if you send a pull request and it has some tests I'll be happy to merge it in.

**Comment by jcrombez** [comment]
Sorry for the delay, i just launched a container on my server, and it seems to work :)

There might be a quote escape issue, not sure if the problem is from the image though...

```
{"message":"10.7.0.5 - - [05/Apr/2016:19:58:52 +0200] \"GET /min/js/main.js HTTP/1.1\" 304 0 \"http://******/forum/\" \"Mozilla/5.0 (Android 5.0.2; Mobile; rv:45.0) Gecko/45.0 Firefox/45.0\"","container_name":"/web-1.web.904efddc","container_id":"bbb3a78b1048d270eb3653c52fdbe976bee9e7e6qc74793f343b1301f456a962","container_image":"****/****latest","hostname":"web-1"}
```

**Comment by dmulter** [comment]
FYI, I'm running into this exact issue regularly and it's prevent log messages getting through other than the first few messages. It doesn't look like that PR ever was completed. Any update on what path makes the most sense? Would it help to send the messages to Loggly via syslog instead of http?

**Comment by iamatypeofwalrus** [comment]
I left notes in the PR but haven't received a response. Happy to work on this a bit this weekend. Syslog or a UDP bulk endpoint makes the most sense to me.

Since I've moved to cloud.docker.com I haven't been using this image, hence why it's in this state.

**Comment by iamatypeofwalrus** [comment]
Working on this now. Moving the adapter to its own directory so it can be tested and using a buffered channel to send requests to the longly bulk endpoint.

**Comment by iamatypeofwalrus** [comment]
I have a working in progress branch under `origin/bulk-endpoint-batching` and a test image under `iamatypeofwalrus/logspout-loggly:bulk`

edit:
It seems to be working fine for me. I tested it by curling my website 200 times

```
for _ in {1..200}; do curl http://glasswaves.co > /dev/null; done
```

and the logs showed up in loggly. If this works for everyone I'll merge into mainline

**Comment by yoo** [comment]
I reworked my pull request on top of your bulk branch with two changes.
1. Send the messages to loggly in the background to prevent the stream timeouts.
2. Add a periodic buffer flush every 10 seconds. If only one container writes logs and crashes
   you maybe never see the error messages.

**Comment by dmulter** [comment]
I pulled :latest and did some testing. For me, it's actually worse as I almost never get any messages through to Loggly. I don't think I'm doing anything silly. Happy to help with debugging if needed, even directly.

**Comment by iamatypeofwalrus** [comment]
That's odd. I've definitely been seeing messages end up in loggly. Do you have a way to saturate the buffer? I believe right now it's 100 messages.

**Comment by iamatypeofwalrus** [comment]
Actually I think I see the bug. We don't reset the timeout count when the timer goes off. So the first time we flush the buffer after the timer it reverts to only sending messages after the buffer is full. 

I'll fix this morning when I get in to work.

**Comment by dmulter** [comment]
My testing has just been hit my app with just a few CURLs. There's usually a dozen or so log messages generated when gunicorn/nginx/scheduler comes up first. I haven't tried any real load, just trying to reliably get the first dozen messages every time I bring up my app.

**Comment by iamatypeofwalrus** [comment]
Pushed out a bug fix. Waiting for docker hub to build and then i'll do some integration tests on it.

**Comment by iamatypeofwalrus** [comment]
[This is the activity](https://www.dropbox.com/s/r02g2r4rlzg2kpm/Screenshot%202016-04-18%2011.31.51.png) from loggly using an image that did not flush after the timeout.

[Here's the activity](https://www.dropbox.com/s/vhya6x31u2u0sb7/Screenshot%202016-04-18%2011.38.51.png) from the fixed image. As you can see I'm now receiving the logs more frequently and we don't have to wait for the buffer to become full before flushing.

**Comment by iamatypeofwalrus** [comment]
@dmulter let me know how the new images are working out for you.

**Comment by dmulter** [comment]
working great now!

**Comment by yoo** [comment]
Somebody is still using the quay.io/eversolve/logspout-loggly image. This image is NOT maintained and was only provided for testing and will be REMOVED in 2 weeks. Please switch to iamatypeofwalrus/logspout-loggly.
