### ISSUE TITLE
Updated to the current version but not seeing tags show up in Loggly

### ISSUE THREAD

**Issue by tbossert** [iamatypeofwalrus/logspout-loggly#8]
I set the env var "LOGGLY_TAGS": "development" but for some reason they aren't being attached to messages when viewed in Loggly.

**Comment by iamatypeofwalrus** [comment]
I see where the bug is. Fixing now.

**Comment by tbossert** [comment]
👍

**Comment by tbossert** [comment]
I also noticed that when I view recent events I am not able to filter them based on json properties of the message.   I can only filter on container info.   Is this expected behavior?   Not sure if it's related but all the keys and values in the message json are escaped it looks like.

**Comment by iamatypeofwalrus** [comment]
I can filter on [JSON properties](https://www.dropbox.com/s/0k31t02bgo9vp6e/Screenshot%202016-04-18%2013.46.37.png?dl=0) of the logglyMessage struct.

Escaping of the log message received from logspout happens when the logglyMessage struct is marshaled. So if your log message is in JSON it will be escaped when it is sent to loggly.

**Comment by tbossert** [comment]
Ahh thanks for that info, I think the reason it isn't parsing is because the output logging of our apps is adding a timestamp/name before the the json string in stdout.  I will modify our logging and see if it resolves it.

Thanks

**Comment by tbossert** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x64396b]

goroutine 92 [running]:
panic(0x86f860, 0xc82000a090)
    /usr/lib/go/src/runtime/panic.go:464 +0x3e6
github.com/iamatypeofwalrus/logspout-loggly/loggly/adapter.(_Adapter).sendRequestToLoggly(0xc820012840, 0xc820366a80)
  /go/src/github.com/iamatypeofwalrus/logspout-loggly/loggly/adapter/adapter.go:132 +0x2fb
created by github.com/iamatypeofwalrus/logspout-loggly/loggly/adapter.(_Adapter).flushBuffer
  /go/src/github.com/iamatypeofwalrus/logspout-loggly/loggly/adapter/adapter.go:111 +0x44b

I see this error several times in the container output

**Comment by iamatypeofwalrus** [comment]
Catching that one in the fix for tags and adding a test for that condition.

**Comment by tbossert** [comment]
👍

**Comment by tbossert** [comment]
Sorry to keep bugging you, but had one more question.  In the loggly interface when I click on "message" in an event it adds this to the search field json.message:"[object Object]"     Not sure if you had any thoughts on why Loggly was seeing it like that.  I tried to search using a nested field but it never finds results.     Thanks in advance.

**Comment by iamatypeofwalrus** [comment]
[Latest commit](https://github.com/iamatypeofwalrus/logspout-loggly/commit/3c34dcc7dc573708bd4bf3595dea11f6fc62ae80) contains a [fix for sending tags to loggly](https://www.dropbox.com/s/ljmbb9639nykf5k/Screenshot%202016-04-18%2015.26.42.png?dl=0) and a bug fix the nil dereference.

**Comment by tbossert** [comment]
I will check it out.  Thanks

**Comment by iamatypeofwalrus** [comment]
@tbossert re the message in loggly: are you logging JSON? With regular logs (think Nginx or apache) clicking on the message [works like you would expect](https://www.dropbox.com/s/98tl86w2f2jjlig/Screenshot%202016-04-18%2015.31.55.png?dl=0)

Happy to merge in a PR that works in your case (logging in JSON) and the default case (line logging). Maybe the loggly team can give you more insight in how it works on their end?

**Comment by tbossert** [comment]
We are using bunyan which logs out to json by default I think.    I will look into this more and reach out when I have more info or a PR.  Thanks again for the help today and quick responses!
