### ISSUE TITLE
Container crashes frequently with nil pointer dereference runtime error

### ISSUE THREAD

**Issue by molsder** [iamatypeofwalrus/logspout-loggly#9]
I'm getting a lot of container crashes with this in the log. Any idea what's happening?

logging      | panic: runtime error: invalid memory address or nil pointer dereference
logging      | [signal 0xb code=0x1 addr=0x0 pc=0x643976]
logging      |
logging      | goroutine 258 [running]:
logging      | panic(0x86f860, 0xc82000a080)
logging      |  /usr/lib/go/src/runtime/panic.go:464 +0x3e6
logging      | github.com/iamatypeofwalrus/logspout-loggly/loggly/adapter.(_Adapter).sendRequestToLoggly(0xc820067800, 0xc82033ad20)
logging      |  /go/src/github.com/iamatypeofwalrus/logspout-loggly/loggly/adapter/adapter.go:110 +0x596
logging      | created by github.com/iamatypeofwalrus/logspout-loggly/loggly/adapter.(_Adapter).flushBuffer
logging      |  /go/src/github.com/iamatypeofwalrus/logspout-loggly/loggly/adapter/adapter.go:105 +0x23a
logging      | # logspout v3.1-dev-custom by gliderlabs
logging      | # adapters: syslog tcp udp loggly raw
logging      | # options : persist:/mnt/routes
logging      | # jobs    : http[logs,routes]:80 pump
logging      | # routes  :
logging      | #   ADAPTER  ADDRESS CONTAINERS  SOURCES OPTIONS
logging      | #   loggly                   map[]

**Comment by iamatypeofwalrus** [comment]
Looks like this can happen when there is an error sending a request to loggly. The resp body may or may not be nil when the err is not nil. 

I can submit a patch tonight.

**Comment by molsder** [comment]
Thanks for the quick response. A patch would be very much appreciated.

**Comment by iamatypeofwalrus** [comment]
Pushed fix. hub.docker.com should be building an image right now.

Let me know how it works out.

**Comment by molsder** [comment]
Thanks! I've installed it on one of the instances and will monitor it for while. I'll let you know how it goes.

**Comment by molsder** [comment]
Looking good still. Hard to prove a negative. The other instances also haven't crashed recently. Makes me wonder if it's something Loggly changed. Anyway, thanks for the fix!
